### ISSUE TITLE
Transparency violation in Parallel_Computing_Lesson4.m

### ISSUE THREAD

**Issue by mikecroucher** [kdeeleymath/Sheffield_January_2016#2]
It works fine in MATLAB 2015a on Linux but I also happened to try it on MATLAB 2015b on Windows 10. On the latter configuration, I get transparency errors. E.g.

```
Error using Parallel_Computing_Lesson_04 (line 24)
Error detected on worker 1.

Caused by:
    Error using codistributed/display (line 24)
    Transparency violation error.
     See Parallel Computing Toolbox documentation about Transparency
```

The worker(s) reporting the error varies from run to run. The issue is caused by the line `display(A)`

Can you confirm that this is the case on your machine for MATLAB 2015b pls?

**Comment by kdeeleymath** [comment]
Thanks Mike. I get the same for MATLAB R2015b. I moved the display commands outside of the spmd block to fix this.

**Comment by mikecroucher** [comment]
Is it a bug in 2015b? I thought the 2015a behaviour was nice!

**Comment by kdeeleymath** [comment]
I think the behaviour is intentional going from R2015a to R2015b. The release notes for R2015b (http://uk.mathworks.com/help/distcomp/release-notes.html) contain a section on "More consistent transparency enforcement."
